version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/libraries/typescript"
    target-branch: "canary"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/libraries/python"
    target-branch: "canary"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "canary"
    schedule:
      interval: "weekly"
