/** @internal Explicit authentication methods supported at upstream token endpoints. */
export type UpstreamTokenEndpointAuthMethod =
  | "client_secret_basic"
  | "client_secret_post"
  | "none";

/** @internal Construction options for the helper-backed upstream OAuth adapter. */
export interface UpstreamOAuthClientOptions {
  /** Upstream authorization endpoint. */
  authorizationEndpoint: string | URL;
  /** Upstream token endpoint. */
  tokenEndpoint: string | URL;
  /** Optional RFC 7009 token revocation endpoint. */
  revocationEndpoint?: string | URL;
  /** Expected RFC 9207 authorization-response issuer, when issuer validation is enabled. */
  issuer?: string | URL;
  /** Require the upstream callback to include `iss`; returned values are checked whenever present. */
  requireAuthorizationResponseIssuer?: boolean;
  /** Pre-registered upstream client identifier. */
  clientId: string;
  /** Client secret required by secret-based authentication methods. */
  clientSecret?: string;
  /** Explicit token endpoint client authentication method. */
  tokenEndpointAuthMethod: UpstreamTokenEndpointAuthMethod;
  /** Extra, non-reserved parameters included in every authorization request. */
  authorizationParams?: Readonly<Record<string, string>>;
  /** Fetch implementation used for upstream requests. */
  fetch?: typeof fetch;
  /** Total timeout covering response headers and response-body streaming. */
  timeoutMs?: number;
  /** Maximum number of response-body bytes read from an upstream endpoint. */
  maxResponseBytes?: number;
  /** Web Crypto random source used for proxy-owned state and nonce values. */
  crypto?: Pick<Crypto, "getRandomValues">;
}

/** @internal Inputs used to construct one upstream authorization request. */
export interface UpstreamAuthorizationRequest {
  /** Redirect URI registered for the upstream client. */
  redirectUri: string | URL;
  /** Requested scopes, either as an OAuth scope string or individual values. */
  scopes?: string | readonly string[];
  /** Whether to generate and bind an OpenID Connect nonce. */
  includeNonce?: boolean;
  /** Explicit upstream RFC 8707 resource indicator for this request only. */
  resource?: string | URL;
  /** Additional non-reserved authorization parameters for this request. */
  extraParams?: Readonly<Record<string, string>>;
}

/** @internal Secrets that bind an authorization response to its original request. */
export interface UpstreamAuthorizationTransaction {
  /** Random OAuth state value owned and persisted by the proxy. */
  readonly state: string;
  /** PKCE verifier generated by the official OAuth helper. */
  readonly codeVerifier: string;
  /** Lexical redirect URI bound to the authorization request. */
  readonly redirectUri: string;
  /** Authorization-request resource binding, which is never auto-forwarded. */
  readonly resource?: string;
  /** Optional OpenID Connect nonce owned by the proxy. */
  readonly nonce?: string;
}

/** @internal An upstream authorization URL and the transaction that must be stored with it. */
export interface UpstreamAuthorizationResult {
  /** URL to which the user agent should be redirected. */
  readonly url: URL;
  /** Transaction required to validate and exchange the authorization response. */
  readonly transaction: UpstreamAuthorizationTransaction;
}

/** @internal Inputs for validating an authorization response and exchanging its code. */
export interface UpstreamAuthorizationCodeExchange {
  /** Callback URL or its already-parsed query parameters. */
  authorizationResponse: URL | URLSearchParams;
  /** Stored transaction returned by the upstream adapter's authorization request. */
  transaction: UpstreamAuthorizationTransaction;
  /** Explicit upstream RFC 8707 resource indicator for this exchange only. */
  resource?: string | URL;
  /** Additional non-reserved token parameters for this request. */
  extraParams?: Readonly<Record<string, string>>;
  /** Optional caller cancellation signal, composed with the configured timeout. */
  signal?: AbortSignal;
}

/** @internal Inputs for an upstream refresh-token grant. */
export interface UpstreamRefreshTokenRequest {
  /** Refresh token from the current token set. */
  refreshToken: string;
  /** Current scope, optionally sent upstream and preserved if the response omits scope. */
  scope?: string;
  /** Explicit upstream RFC 8707 resource indicator for this refresh only. */
  resource?: string | URL;
  /** Additional non-reserved token parameters for this request. */
  extraParams?: Readonly<Record<string, string>>;
  /** Optional caller cancellation signal, composed with the configured timeout. */
  signal?: AbortSignal;
}

/** @internal Inputs for RFC 7009 upstream token revocation. */
export interface UpstreamTokenRevocationRequest {
  /** Token to revoke. */
  token: string;
  /** Optional hint describing the submitted token. */
  tokenTypeHint?: "access_token" | "refresh_token" | string;
  /** Additional non-reserved revocation parameters for this request. */
  extraParams?: Readonly<Record<string, string>>;
  /** Optional caller cancellation signal, composed with the configured timeout. */
  signal?: AbortSignal;
}

/** @internal Normalized successful token response returned by the upstream adapter. */
export interface UpstreamTokenSet {
  /** Upstream access token. */
  readonly accessToken: string;
  /** Upstream token type. */
  readonly tokenType: string;
  /** Lifetime in seconds, when returned by the upstream. */
  readonly expiresIn?: number;
  /** Refresh token, including the previous token when a refresh response omits rotation. */
  readonly refreshToken?: string;
  /** Granted scope, including the previous scope when a refresh response omits it. */
  readonly scope?: string;
  /** Unverified ID-token string. This adapter never decodes or trusts its claims. */
  readonly idToken?: string;
}
