import { copyFileSync, existsSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const action = process.argv[2];
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryReadme = resolve(scriptDirectory, "../../../README.md");
const packageReadme = resolve(scriptDirectory, "../packages/server/README.md");
const generatedMarker = resolve(
  scriptDirectory,
  "../packages/server/.npm-readme-generated"
);

if (action === "prepare") {
  if (existsSync(packageReadme) && !existsSync(generatedMarker)) {
    throw new Error(
      `Refusing to overwrite existing package README: ${packageReadme}`
    );
  }

  copyFileSync(repositoryReadme, packageReadme);
  writeFileSync(generatedMarker, "generated by package-readme.mjs\n");
} else if (action === "cleanup") {
  if (existsSync(generatedMarker)) {
    rmSync(packageReadme, { force: true });
    rmSync(generatedMarker, { force: true });
  }
} else {
  throw new Error(`Expected \"prepare\" or \"cleanup\", received: ${action}`);
}
