export const MCP_APPS_CONFIG = {
  TIMEOUTS: {
    TOOL_CALL: 600000,
    ANIMATION: 300,
  },
  DIMENSIONS: {
    PIP_WIDTH: 768,
    PIP_MAX_WIDTH: 700,
    PIP_HEIGHT: 400,
    DEFAULT_HEIGHT: 400,
  },
} as const;
