/**
 * Optional integration with Better Auth's MCP authorization engine.
 *
 * @packageDocumentation
 */

import type { requireMcpAuth, RequireMcpAuthOptions } from "@better-auth/mcp";
import { createResourceServerChallenge } from "@better-auth/oauth-provider";
import type { AuthInfo } from "@modelcontextprotocol/server";
import { APIError, isAPIError } from "better-auth/api";
import {
  CLIENT_ASSERTION_TYPE,
  createDpopReplayStore,
  decodeBasicCredentials,
  isInsufficientScopeError,
  parseAccessTokenAuthorization,
  requestToResourceInput,
  verifyAccessTokenRequest,
} from "better-auth/oauth2";
import { decodeJwt, type JWTPayload } from "jose";

import type { RequestAuthOptions } from "./request-auth.js";
import { validateOAuthResource } from "./internal.js";

export {
  createNativeMcpAuth,
  type NativeMcpAuth,
  type NativeMcpAuthOptions,
} from "./better-auth-native-engine.js";
export type { NativeOAuthUser } from "./better-auth-native.js";
export {
  createOAuthMcpAuth,
  type OAuthMcpAuth,
  type OAuthMcpAuthOptions,
  type OAuthMcpProviderOptions,
} from "./better-auth-upstream-engine.js";

/** Application-owned Better Auth instance configured with its `mcp()` plugin. */
export type BetterAuthMcpInstance = Parameters<typeof requireMcpAuth>[0] & {
  /** Dispatches the original request to Better Auth's installed endpoints. */
  handler: (request: Request) => Promise<Response>;
  /** Server APIs generated by the installed OAuth provider. */
  api: Record<string, unknown>;
};

/** Options for {@link betterAuthMcp}. */
export interface BetterAuthMcpOptions<TUser> {
  /** Configured engine instance; its storage and lifecycle remain app-owned. */
  auth: BetterAuthMcpInstance;
  /** Exact public MCP resource also configured in the engine's `mcp()` plugin. */
  resource: URL | string;
  /** Required access-token scopes, enforced by the engine on every request. */
  requiredScopes?: readonly string[];
  /** Optional engine proof-validation settings, including a shared replay store. */
  dpop?: RequireMcpAuthOptions["dpop"];
  /**
   * Optional application session check after token and proof verification.
   * Return `invalid` for an ended or mismatched session and `unavailable` for
   * a temporary identity-store failure. No OAuth response construction is needed.
   * Unexpected errors are handled as unavailable by the SDK's request-auth mode.
   */
  checkSession?: (
    claims: JWTPayload,
    request: Request
  ) => Promise<"valid" | "invalid" | "unavailable">;
  /**
   * Serializes engine token/revoke operations across application instances.
   * The default waits up to one second for the same client's active operation
   * within this process, then returns 503 before calling the engine if still busy.
   * Operations are never replayed. Multi-process deployments must supply a shared
   * store guard because engine 1.7.4 does not atomically invalidate refresh
   * families during concurrent rotation/revocation.
   */
  runTokenOperation?: (
    /** Unverified request hint used only to select the serialization key. */
    clientId: string,
    operation: () => Promise<Response>
  ) => Promise<Response>;
  /** Maps verified claims in `authInfo.extra.payload` into typed tool identity. */
  mapAuthInfo: RequestAuthOptions<TUser>["mapAuthInfo"];
}

/** Engine authentication and route dispatch for an mcp-use server. */
export interface BetterAuthMcpIntegration<TUser> {
  /** Pass this to `MCPServer` as its mutually exclusive `requestAuth` mode. */
  requestAuth: RequestAuthOptions<TUser>;
  /**
   * Dispatches the auth namespace and discovery aliases to the engine.
   * Returns `undefined` for other routes. Mount before MCP/body parsing and
   * forward the returned Response, including all Set-Cookie headers, unchanged.
   * Auth-namespace POST bodies are limited to 64 KiB and 10 seconds.
   */
  handle: (request: Request) => Promise<Response | undefined>;
}

const activeTokenClients = new WeakMap<
  BetterAuthMcpInstance,
  Map<string, Promise<void>>
>();

/**
 * Connects an application-owned Better Auth MCP engine to mcp-use.
 *
 * The engine owns discovery, client admission, PKCE, tokens and request proof
 * validation. Configure CIMD or explicit legacy DCR in that engine instance.
 * This helper uses JWT access tokens and the engine's database-backed DPoP
 * replay protection; it does not create an auth server or migrate its database.
 * Rejected DPoP proofs use a generic challenge description if the engine cannot
 * serialize its own description. Unexpected verification failures still throw.
 *
 * @param options - Engine, exact resource, identity mapping and session policy.
 * @returns Request authentication and raw engine route dispatch.
 * @throws A `TypeError` for inconsistent engine/resource metadata or overlapping routes.
 */
export async function betterAuthMcp<TUser>(
  options: BetterAuthMcpOptions<TUser>
): Promise<BetterAuthMcpIntegration<TUser>> {
  const { auth } = options;
  const resource = new URL(options.resource);
  validateOAuthResource(resource, resource.pathname);
  const context = await auth.$context;
  const baseURL = new URL(context.baseURL);
  const basePath = baseURL.pathname.replace(/\/+$/, "");
  if (
    !basePath ||
    resource.pathname === basePath ||
    resource.pathname.startsWith(`${basePath}/`)
  ) {
    throw new TypeError(
      "Better Auth needs an auth namespace separate from MCP"
    );
  }

  const getMetadata = auth.api["getOAuthServerConfig"];
  if (!isMetadataApi(getMetadata)) {
    throw new TypeError("Better Auth must include its mcp() plugin");
  }
  const metadata = await getMetadata();
  if (
    !isRecord(metadata) ||
    typeof metadata["issuer"] !== "string" ||
    typeof metadata["token_endpoint"] !== "string" ||
    typeof metadata["jwks_uri"] !== "string"
  ) {
    throw new TypeError("betterAuthMcp requires the engine's JWT/JWKS support");
  }
  const issuerPath = new URL(metadata["issuer"]).pathname.replace(/\/$/, "");
  const resourcePath = resource.pathname.replace(/\/$/, "");
  const resourceMetadataPath = `/.well-known/oauth-protected-resource${resourcePath}`;
  const resourceMetadataResponse = await auth.handler(
    new Request(new URL(resourceMetadataPath, resource.origin))
  );
  if (!resourceMetadataResponse.ok) {
    throw new TypeError("Better Auth must include its mcp() plugin");
  }
  const resourceMetadata: unknown = await resourceMetadataResponse.json();
  if (
    !isRecord(resourceMetadata) ||
    resourceMetadata["resource"] !== resource.href ||
    !Array.isArray(resourceMetadata["authorization_servers"]) ||
    !resourceMetadata["authorization_servers"].includes(metadata["issuer"])
  ) {
    throw new TypeError(
      "Better Auth metadata must match the MCP resource and issuer"
    );
  }

  const discoveryPaths = new Set([
    `/.well-known/oauth-authorization-server${issuerPath}`,
    `${issuerPath}/.well-known/oauth-authorization-server`,
    `${issuerPath}/.well-known/openid-configuration`,
    "/.well-known/oauth-protected-resource",
    resourceMetadataPath,
  ]);
  const tokenPaths = new Set([
    new URL(metadata["token_endpoint"]).pathname,
    ...(typeof metadata["revocation_endpoint"] === "string"
      ? [new URL(metadata["revocation_endpoint"]).pathname]
      : []),
  ]);
  const runTokenOperation =
    options.runTokenOperation ??
    ((clientId: string, operation: () => Promise<Response>) =>
      runLocalTokenOperation(auth, clientId, operation));
  const verification: Parameters<typeof verifyAccessTokenRequest>[1] = {
    verifyOptions: { issuer: metadata["issuer"], audience: resource.href },
    jwksUrl: metadata["jwks_uri"],
    ...(options.requiredScopes !== undefined && {
      requiredScopes: options.requiredScopes,
    }),
    dpop: {
      ...options.dpop,
      replayStore:
        options.dpop?.replayStore ??
        createDpopReplayStore(context.internalAdapter),
    },
  };
  const challengeOptions = {
    ...(options.requiredScopes !== undefined && {
      challengeScopes: options.requiredScopes,
    }),
    ...(options.dpop?.signingAlgorithms !== undefined && {
      dpopSigningAlgorithms: options.dpop.signingAlgorithms,
    }),
  };

  return {
    requestAuth: {
      resource,
      mapAuthInfo: options.mapAuthInfo,
      async authenticate(request) {
        let claims: JWTPayload;
        try {
          // Verify once: proof verification also reserves its replay identifier.
          claims = await verifyAccessTokenRequest(
            requestToResourceInput(request),
            verification
          );
        } catch (error) {
          return engineChallengeResponse(
            error,
            resource.href,
            challengeOptions
          );
        }

        const authorization = parseAccessTokenAuthorization(
          request.headers.get("authorization")
        );
        if (
          !authorization?.token ||
          typeof claims["client_id"] !== "string" ||
          !claims["client_id"] ||
          typeof claims.exp !== "number"
        ) {
          return invalidSessionResponse(resource.href, options.requiredScopes);
        }
        if (options.checkSession) {
          let status: "valid" | "invalid" | "unavailable";
          try {
            status = await options.checkSession(claims, request);
          } catch (error) {
            if (!isInsufficientScopeError(error)) throw error;
            return engineChallengeResponse(
              error,
              resource.href,
              challengeOptions
            );
          }
          if (status === "invalid") {
            return invalidSessionResponse(
              resource.href,
              options.requiredScopes
            );
          }
          if (status !== "valid") {
            return Response.json(
              { error: "temporarily_unavailable" },
              { status: 503, headers: { "Cache-Control": "no-store" } }
            );
          }
        }
        return {
          token: authorization.token,
          clientId: claims["client_id"],
          scopes:
            typeof claims["scope"] === "string"
              ? claims["scope"].split(" ")
              : [],
          expiresAt: claims.exp,
          resource: new URL(resource.href),
          extra: { payload: claims },
        } satisfies AuthInfo;
      },
    },
    async handle(request) {
      const pathname = new URL(request.url).pathname;
      const path = auth.options.advanced?.skipTrailingSlashes
        ? pathname.replace(/\/+$/, "") || "/"
        : pathname;
      if (
        path === basePath ||
        path.startsWith(`${basePath}/`) ||
        discoveryPaths.has(path)
      ) {
        const bounded =
          request.method === "POST" &&
          (path === basePath || path.startsWith(`${basePath}/`))
            ? await boundedAuthRequest(request)
            : request;
        if (bounded instanceof Response) return bounded;
        if (request.method === "POST" && tokenPaths.has(path)) {
          const clientId = await operationClient(bounded);
          if (!clientId) return bodyFailure(400);
          return runTokenOperation(clientId, () => auth.handler(bounded));
        }
        return auth.handler(bounded);
      }
      return undefined;
    },
  };
}

function engineChallengeResponse(
  error: unknown,
  resource: string,
  options: Parameters<typeof createResourceServerChallenge>[2]
): Response {
  let challenge: ReturnType<typeof createResourceServerChallenge>;
  try {
    challenge = createResourceServerChallenge(error, resource, options);
  } catch (formatError) {
    // Better Auth 1.7.4 can reject quotes in its own DPoP error description.
    // Only replace that description after the engine has rejected the proof.
    if (
      !isAPIError(error) ||
      error.status !== "UNAUTHORIZED" ||
      error.body?.error !== "invalid_dpop_proof" ||
      !(formatError instanceof TypeError) ||
      formatError.message !== "invalid error_description"
    )
      throw formatError;
    challenge = createResourceServerChallenge(
      new APIError("UNAUTHORIZED", {
        error: "invalid_dpop_proof",
        error_description: "Invalid DPoP proof",
      }),
      resource,
      options
    );
  }
  if (!challenge) throw error;
  return Response.json(
    {
      jsonrpc: "2.0",
      error: { code: -32000, message: challenge.message },
      id: null,
    },
    { status: challenge.statusCode, headers: challenge.headers }
  );
}

function invalidSessionResponse(
  resource: string,
  scopes: readonly string[] | undefined
): Response {
  const challenge = createResourceServerChallenge(
    new APIError("UNAUTHORIZED", { message: "Invalid access-token session" }),
    resource,
    scopes === undefined ? undefined : { challengeScopes: scopes }
  );
  if (!challenge) throw new Error("Engine could not build its auth challenge");
  return Response.json(
    {
      jsonrpc: "2.0",
      error: { code: -32000, message: challenge.message },
      id: null,
    },
    { status: challenge.statusCode, headers: challenge.headers }
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isMetadataApi(value: unknown): value is () => Promise<unknown> {
  return typeof value === "function";
}

async function boundedAuthRequest(
  request: Request
): Promise<Request | Response> {
  const reader = request.body?.getReader();
  if (!reader) return request;
  const chunks: Uint8Array[] = [];
  let length = 0;
  let timer: ReturnType<typeof setTimeout> | undefined;
  const deadline = new Promise<never>((_resolve, reject) => {
    timer = setTimeout(() => {
      reject(new DOMException("Authentication body timeout", "TimeoutError"));
      void reader.cancel().catch(() => {});
    }, 10_000);
  });
  try {
    while (true) {
      const { value, done } = await Promise.race([reader.read(), deadline]);
      if (done) break;
      length += value.byteLength;
      if (length > 65_536) {
        void reader.cancel().catch(() => {});
        return bodyFailure(413);
      }
      chunks.push(value);
    }
  } catch (error) {
    return bodyFailure(
      error instanceof DOMException && error.name === "TimeoutError" ? 408 : 400
    );
  } finally {
    clearTimeout(timer);
    reader.releaseLock();
  }
  const body = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) {
    body.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return new Request(request, { body });
}

function bodyFailure(status: number): Response {
  return Response.json(
    { error: "invalid_request" },
    { status, headers: { "Cache-Control": "no-store" } }
  );
}

async function operationClient(request: Request): Promise<string | undefined> {
  try {
    let body: Record<string, unknown>;
    const contentType = request.headers.get("content-type")?.split(";")[0];
    if (contentType?.trim().toLowerCase() === "application/json") {
      const parsed: unknown = await request.clone().json();
      if (!isRecord(parsed)) return undefined;
      body = parsed;
    } else {
      const parsed = new URLSearchParams(await request.clone().text());
      for (const field of [
        "client_id",
        "client_assertion",
        "client_assertion_type",
      ]) {
        if (parsed.getAll(field).length > 1) return undefined;
      }
      body = Object.fromEntries(parsed);
    }
    const bodyId = body["client_id"];
    if (bodyId !== undefined && (typeof bodyId !== "string" || !bodyId)) {
      return undefined;
    }
    let candidate = typeof bodyId === "string" ? bodyId : undefined;
    const assertion = body["client_assertion"];
    const assertionType = body["client_assertion_type"];
    if (
      (assertion !== undefined && typeof assertion !== "string") ||
      (assertionType !== undefined && typeof assertionType !== "string")
    ) {
      return undefined;
    }
    if (assertion && assertionType === CLIENT_ASSERTION_TYPE) {
      // This is only a lock-key hint. The unchanged request still reaches the
      // engine, which verifies signature, issuer, subject, audience and replay.
      const claims = decodeJwt(assertion);
      const hint = claims.sub ?? claims.iss;
      if (
        typeof hint !== "string" ||
        !hint ||
        (candidate !== undefined && candidate !== hint) ||
        (claims.iss !== undefined && claims.iss !== hint)
      ) {
        return undefined;
      }
      candidate = hint;
    }
    const authorization = request.headers.get("authorization");
    if (authorization === null) {
      return candidate;
    }
    const { clientId } = decodeBasicCredentials(authorization);
    return clientId && (candidate === undefined || candidate === clientId)
      ? clientId
      : undefined;
  } catch {
    return undefined;
  }
}

async function runLocalTokenOperation(
  auth: BetterAuthMcpInstance,
  clientId: string,
  operation: () => Promise<Response>
): Promise<Response> {
  let active = activeTokenClients.get(auth);
  if (!active) {
    active = new Map();
    activeTokenClients.set(auth, active);
  }
  const deadline = performance.now() + 1_000;
  while (active.has(clientId)) {
    const remaining = deadline - performance.now();
    let timer: ReturnType<typeof setTimeout> | undefined;
    const available =
      remaining > 0 &&
      (await Promise.race([
        active.get(clientId)!.then(() => true),
        new Promise<false>((resolve) => {
          timer = setTimeout(() => resolve(false), remaining);
        }),
      ]));
    clearTimeout(timer);
    if (!available || performance.now() >= deadline) {
      return Response.json(
        { error: "temporarily_unavailable" },
        {
          status: 503,
          headers: { "Cache-Control": "no-store", "Retry-After": "1" },
        }
      );
    }
  }
  let release!: () => void;
  active.set(clientId, new Promise<void>((resolve) => (release = resolve)));
  try {
    return await operation();
  } finally {
    active.delete(clientId);
    release();
  }
}
