import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect } from "vitest";
import { emptyTest as it } from "./fixtures.js";

import {
  renderMcpEnvDeclaration,
  syncMcpEnvDeclaration,
} from "../../src/cli/mcp-env-declaration.js";

describe("renderMcpEnvDeclaration", () => {
  it.each([
    ["/project/index.ts", "./index.js"],
    ["/project/src/index.tsx", "./src/index.js"],
    ["/project/src/index.mts", "./src/index.mjs"],
    ["/project/src/index.cts", "./src/index.cjs"],
    ["/project/server.mjs", "./server.mjs"],
  ])("maps %s to the runtime import %s", (entry, expected) => {
    expect(renderMcpEnvDeclaration("/project", entry)).toContain(
      `tools: typeof import(${JSON.stringify(expected)})`
    );
  });

  it("includes the framework-owned Vite client types", () => {
    expect(renderMcpEnvDeclaration("/project", "/project/index.ts")).toContain(
      'import "mcp-use/vite-client"'
    );
  });
});

describe("syncMcpEnvDeclaration", () => {
  it("creates a missing declaration", async ({ project }) => {
    const { cwd } = project;

    await expect(
      syncMcpEnvDeclaration(cwd, join(cwd, "src", "index.ts"))
    ).resolves.toBe("created");
    await expect(
      readFile(join(cwd, "mcp-env.d.ts"), "utf8")
    ).resolves.toContain('tools: typeof import("./src/index.js")');
  });

  it("refreshes a declaration generated by an earlier mcp-use version", async ({
    project,
  }) => {
    const { cwd } = project;
    const declaration = join(cwd, "mcp-env.d.ts");
    await writeFile(
      declaration,
      "// mcp-use generated env declaration\nlegacy\n"
    );

    await expect(
      syncMcpEnvDeclaration(cwd, join(cwd, "server.ts"))
    ).resolves.toBe("updated");
    await expect(readFile(declaration, "utf8")).resolves.toContain(
      'tools: typeof import("./server.js")'
    );
  });

  it("does not overwrite a user-owned declaration", async ({ project }) => {
    const { cwd } = project;
    const declaration = join(cwd, "mcp-env.d.ts");
    const contents = "// custom declaration\nexport {};\n";
    await writeFile(declaration, contents);

    await expect(
      syncMcpEnvDeclaration(cwd, join(cwd, "index.ts"))
    ).resolves.toBe("user-owned");
    await expect(readFile(declaration, "utf8")).resolves.toBe(contents);
  });
});
