 

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DotwellKnownOauthProtectedResourceSplatRouteImport } from "./routes/[.]well-known.oauth-protected-resource.$";
import { Route as ApiMcpSplatRouteImport } from "./routes/api.mcp.$";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DotwellKnownOauthProtectedResourceSplatRoute =
  DotwellKnownOauthProtectedResourceSplatRouteImport.update({
    id: "/.well-known/oauth-protected-resource/$",
    path: "/.well-known/oauth-protected-resource/$",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiMcpSplatRoute = ApiMcpSplatRouteImport.update({
  id: "/api/mcp/$",
  path: "/api/mcp/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/.well-known/oauth-protected-resource/$": typeof DotwellKnownOauthProtectedResourceSplatRoute;
  "/api/mcp/$": typeof ApiMcpSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/.well-known/oauth-protected-resource/$": typeof DotwellKnownOauthProtectedResourceSplatRoute;
  "/api/mcp/$": typeof ApiMcpSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/.well-known/oauth-protected-resource/$": typeof DotwellKnownOauthProtectedResourceSplatRoute;
  "/api/mcp/$": typeof ApiMcpSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/.well-known/oauth-protected-resource/$" | "/api/mcp/$";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/.well-known/oauth-protected-resource/$" | "/api/mcp/$";
  id:
    | "__root__"
    | "/"
    | "/.well-known/oauth-protected-resource/$"
    | "/api/mcp/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DotwellKnownOauthProtectedResourceSplatRoute: typeof DotwellKnownOauthProtectedResourceSplatRoute;
  ApiMcpSplatRoute: typeof ApiMcpSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/.well-known/oauth-protected-resource/$": {
      id: "/.well-known/oauth-protected-resource/$";
      path: "/.well-known/oauth-protected-resource/$";
      fullPath: "/.well-known/oauth-protected-resource/$";
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/mcp/$": {
      id: "/api/mcp/$";
      path: "/api/mcp/$";
      fullPath: "/api/mcp/$";
      preLoaderRoute: typeof ApiMcpSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DotwellKnownOauthProtectedResourceSplatRoute:
    DotwellKnownOauthProtectedResourceSplatRoute,
  ApiMcpSplatRoute: ApiMcpSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
