// Auto-generated by scripts/generate-version.mjs - DO NOT EDIT
// This file is regenerated during build to embed the package version
export const VERSION = "1.33.0";

/**
 * Get the package version.
 * The version is embedded at build time via scripts/generate-version.mjs
 * Works in all environments (Node.js, browser, Cloudflare Workers, Deno, etc.)
 */
export function getPackageVersion(): string {
  return VERSION;
}
