// Auto-generated by scripts/generate-version.mjs - DO NOT EDIT
// This file is regenerated during build to embed the package version
export const VERSION = "0.22.2";

/**
 * Get the inspector package version.
 * The version is embedded at build time via scripts/generate-version.mjs
 * Works in all environments (Node.js, browser, Cloudflare Workers, Deno, etc.)
 */
export function getInspectorVersion(): string {
  return VERSION;
}
