name: CI

on:
  push:
    branches: [main, canary]
  pull_request:
    branches: [main, canary]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
      typescript: ${{ steps.filter.outputs.typescript }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - 'libraries/python/**'
            typescript:
              - 'libraries/typescript/**'

  # Python Jobs
  python-lint:
    needs: detect-changes
    if: needs.detect-changes.outputs.python == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint with ruff
        run: |
          ruff check .
      - name: Format check with ruff
        run: |
          ruff format --check .

  python-unit-tests:
    needs: python-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    defaults:
      run:
        working-directory: libraries/python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,anthropic,openai,search,e2b]
      - name: Test with pytest
        run: |
          pytest tests/unit

  python-transport-tests:
    needs: python-lint
    name: "python-transport/${{ matrix.transport }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        transport: [stdio, sse, streamable_http]
    defaults:
      run:
        working-directory: libraries/python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install uv
        run: |
          pip install uv
      - name: Install dependencies
        run: |
          uv pip install --system .[dev,anthropic,openai,search,e2b]
      - name: Run integration tests for ${{ matrix.transport }} transport
        run: |
          pytest tests/integration/transports/test_${{ matrix.transport }}.py

  python-primitive-tests:
    needs: python-lint
    name: "python-primitive/${{ matrix.primitive }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        primitive:
          [
            sampling,
            tools,
            resources,
            prompts,
            elicitation,
            notifications,
            auth,
          ]
    defaults:
      run:
        working-directory: libraries/python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install uv
        run: |
          pip install uv
      - name: Install dependencies
        run: |
          uv pip install --system .[dev,anthropic,openai,search,e2b]
      - name: Run integration tests for ${{ matrix.primitive }} primitive
        run: |
          pytest tests/integration/primitives/test_${{ matrix.primitive }}.py

  python-integration-tests:
    needs: python-lint
    name: "python-integration"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install uv
        run: |
          pip install uv
      - name: Install dependencies
        run: |
          uv pip install --system .[dev,anthropic,openai,search,e2b]
      - name: Run other integration tests
        run: |
          pytest tests/integration/others/

  # TypeScript Jobs
  typescript-lint:
    needs: detect-changes
    if: needs.detect-changes.outputs.typescript == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: libraries/typescript/pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Linter
        run: pnpm lint

  typescript-build:
    needs: typescript-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: libraries/typescript/pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Packages
        run: pnpm build

  typescript-test:
    needs: typescript-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: libraries/typescript/pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Packages
        run: pnpm build

      - name: Run Tests
        run: pnpm test

  typescript-changeset-check:
    needs: detect-changes
    if: needs.detect-changes.outputs.typescript == 'true' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: libraries/typescript/pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check for Changesets
        run: |
          if [ -n "$(ls -A .changeset/*.md 2>/dev/null | grep -v README.md)" ]; then
            echo "✅ Changeset found"
            pnpm changeset status --since=origin/main
          else
            echo "⚠️ No changeset found. If this PR includes changes that should be published, please add a changeset:"
            echo "  pnpm changeset"
            echo ""
            echo "If this PR doesn't require a changeset (docs, tests, internal changes), you can ignore this message."
          fi
