name: Transport Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  transports:
    name: "Transport: ${{ matrix.transport }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        transport: [stdio, sse, streamableHttp]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install project with dev and optional extras similar to unit tests environment
          pip install .[dev,anthropic,openai,search,e2b]

      - name: Lint with ruff
        run: |
          ruff check .

      - name: Run integration tests for ${{ matrix.transport }} transport
        run: |
          pytest tests/integration/transports/${{ matrix.transport }}
