name: TypeScript Release Canary

on:
  push:
    branches:
      - canary
    paths:
      - "libraries/typescript/**"
      - ".github/workflows/typescript-release-canary.yml"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release Canary
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"
          cache-dependency-path: libraries/typescript/pnpm-lock.yaml
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        working-directory: libraries/typescript
        run: pnpm install --no-frozen-lockfile

      - name: Build Packages
        working-directory: libraries/typescript
        run: pnpm build

      - name: Enter Prerelease Mode
        working-directory: libraries/typescript
        run: |
          if [ ! -f .changeset/pre.json ]; then
            echo "Entering canary prerelease mode..."
            pnpm changeset pre enter canary
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .changeset/pre.json
            git commit -m "chore: enter canary prerelease mode" || echo "No changes to commit"
            git push
          else
            echo "Already in prerelease mode"
          fi

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          version: cd libraries/typescript && pnpm changeset version
          publish: cd libraries/typescript && pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_ORG }}
