name: TypeScript Changeset Check

on:
  pull_request:
    branches:
      - main
    paths:
      - "libraries/typescript/**"

jobs:
  check:
    name: Check for Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"
          cache-dependency-path: libraries/typescript/pnpm-lock.yaml

      - name: Install Dependencies
        working-directory: libraries/typescript
        run: pnpm install --no-frozen-lockfile

      - name: Check for changesets
        working-directory: libraries/typescript
        run: |
          # Get the source branch name
          SOURCE_BRANCH="${{ github.head_ref }}"
          echo "Source branch: $SOURCE_BRANCH"

          # Special handling for canary -> main merges
          if [ "$SOURCE_BRANCH" = "canary" ]; then
            echo "🐤 Merging from canary branch - special checks apply"
            
            # Check if pre.json exists (should NOT exist - should be exited before PR)
            if [ -f .changeset/pre.json ]; then
              echo "❌ ERROR: pre.json still exists!"
              echo ""
              echo "Before merging canary → main, you must exit prerelease mode."
              echo ""
              echo "To exit prerelease mode:"
              echo "1. Go to Actions tab"
              echo "2. Run 'TypeScript Exit Prerelease Mode' workflow on canary branch"
              echo "3. Type 'exit' to confirm"
              echo "4. Wait for the workflow to complete"
              echo "5. Then create/update this PR"
              echo ""
              exit 1
            else
              echo "✅ Prerelease mode already exited (pre.json not found)"
            fi
            
            # Check if there are unconsumed changesets (there shouldn't be)
            if [ -n "$(find .changeset -name '*.md' -not -name 'README.md' -print -quit)" ]; then
              echo "⚠️  Warning: Unconsumed changesets found when merging from canary"
              echo "This might indicate that changesets weren't versioned/published on canary"
            else
              echo "✅ No unconsumed changesets (expected for canary merge)"
            fi
            
            echo "✅ Canary merge check passed"
            exit 0
          fi

          # Standard changeset check for other branches
          if [ -n "$(find .changeset -name '*.md' -not -name 'README.md' -print -quit)" ]; then
            echo "✅ Changeset found"
            exit 0
          else
            # Check if any package files changed
            if git diff --name-only origin/main...HEAD | grep -E "^libraries/typescript/packages/.+\.(ts|tsx|js|jsx|json)$" > /dev/null; then
              echo "❌ No changeset found but package files were modified"
              echo "Please add a changeset by running: pnpm changeset"
              exit 1
            else
              echo "✅ No package changes detected, skipping changeset requirement"
              exit 0
            fi
          fi
